admins: []
forwards:
- source: -1001230197447
  dest:
  - -1001614264545
  offset: 6001
  end: 6000
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@Telugudubbing_movies - ': 'Join @MVS_REQ - '
      '⭕ @Tamil_Seriesz
⭕ @Tv_Web_Seriesz
⭕ @Tamil_Old_Flims
⭕ @Tamil_DUB_Movies
⭕ @Sons_of_TamilRockers
⭕ @Tamil_HD_Movies_Requests
➠ Group : 🎯
⭕ @Discussion_HD_Movies 💬
➠ Click Here More Channels
⭕ @Tamil_LinkzZ (All in One)': 'Join @MVS_REQ - '
    regex: true
