admins: []
forwards:
- source: -1001255398384
  dest:
  - -1001712638055
  offset: 1
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@Telugudubbing_movies - ': 'Join @MVS_REQ - '
      regex: true
