admins: []
forwards:
- source: -1001598915083
  dest:
  - -1001158771162
  - -1001462976182
  offset: 1218
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@MovieJunction - ': 'Join @REQ_MVS - '
      '@MovieJunctionChannel': Join @REQ_MVS
      regex: true
